### ISSUE TITLE
New releases are not tagged

### ISSUE THREAD

**Issue by QuLogic** [rstudio/httpuv#100]
The latest tag on GitHub appears to be `v/1/3/3` (why slashes?), but on CRAN, the latest version is 1.3.5. It seems that a few tags are missing here.

**Comment by wch** [comment]
Thanks for filing the issue. I also noticed this just yesterday. I personally prefer dots instead of slashes - we'll see if it make sense to switch now.

**Comment by jcheng5** [comment]
FYI, I used slashes because some GUI git clients will treat paths with slashes as folders.

**Comment by wch** [comment]
I've tagged all the CRAN releases. @jcheng5 and I discussed this, and we agreed to name them like `v1.3.3`.

**Comment by QuLogic** [comment]
Thanks!
