### ISSUE TITLE
report why server creation fails

### ISSUE THREAD

**Issue by aronatkins** [rstudio/httpuv#101]
We have some automated tests which occasionally fail to start a server (listening on a port that should be available). Unfortunately, all we can do is retry (trapping for the "Failed to create server" error message). We get no further context about the cause of the error.

It would be good if there were a way to obtain the bind failure reason (or other startup failure). `createTcpServer` only reacts to a non-zero code by returning `NULL`:
https://github.com/rstudio/httpuv/blob/c2e9011db678ade369abb8cc81395ecdcf845c72/src/http.cpp#L75-L108

The underlying failure reason should be extracted with `uv_strerror(r)` and somehow get exposed to the caller.

**Comment by wch** [comment]
Reopening because I never actually merged the fix!
