### ISSUE TITLE
Build fails with certain locales

### ISSUE THREAD

**Issue by palday** [rstudio/httpuv#11]
Hello,

the build for httpuv conistently failed for me with 
    g++: error: [1]: No such file or directory

Upon closer examination the file in question was my locale:

```
g++: error: "LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=en_US.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=C;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=C": No such file or directory
```

which I had set in `.Rprofile` with `Sys.setlocale(category = "LC_ALL", locale = "en_US.UTF-8")`. I've never had another package fail because of my locale, but the build worked after commenting out that line and restarting R.

Platform: Linux Mint Debian Edition with CRAN-Deb install of R, but most packages installed via `install.packages()`

**Comment by wch** [comment]
This is probably the same as #47. In general, if the .Rprofile prints to the console, it can cause problems with installing packages.
