### ISSUE TITLE
Should have better error message when startServer fails

### ISSUE THREAD

**Issue by wch** [rstudio/httpuv#139]
"Failed to create server" is not very informative:
https://github.com/rstudio/httpuv/blob/master/R/httpuv.R#L426

**Comment by aronatkins** [comment]
Code ref not against master: https://github.com/rstudio/httpuv/blob/5d59a3cb62bc642ca25b44fca4f226bd1f3d394a/R/httpuv.R#L446

**Comment by aronatkins** [comment]
Related to https://github.com/rstudio/httpuv/issues/101

**Comment by wch** [comment]
This was fixed by #146.
