### ISSUE TITLE
Cannot install on windows XP

### ISSUE THREAD

**Issue by stanstrup** [rstudio/httpuv#140]
Hi,

I have build a shiny app that was supposed to run on an old machine that is used in the lab to control machines (making updating not something we dare to attempt).

I am however unable to run it because `httpuv` fails.
If I install it I get a pop-up saying: "The procedure entry point sprintf_s could not be located in the dynamic link library msvcrt.dll."

And in R this error:

```r
> install_local("F:/httpuv_1.4.3.zip")
Installation failed: unable to load shared object 'C:/Documents and Settings/ins
trument/Desktop/WlogBook/packrat/lib/i386-w64-mingw32/3.5.0/git2r/libs/i386/git2
r.dll':
  LoadLibrary failure:  The specified procedure could not be found.
```

It seems to be the exact same problem that was solved here for jsonlite: https://github.com/jeroen/jsonlite/issues/45
I was hoping you could make a fix too for httpuv...

If I copy the package from another machine and run the app I get the following in a pop-up `"The procedure entry point ConvertInterfaceIndexToLuid could not be located in the dynamic link library IPHLPAPI.DLL"`

**Comment by wch** [comment]
This looks like a problem with the git2r package. I suggest filing an issue in that repository: https://github.com/ropensci/git2r

**Comment by stanstrup** [comment]
Hi again.

I managed to solve the git2r problem by downgrading to a previous version that works on XP.

Now I am back to the same problem with `httpuv`.

```
> library(httpuv)
Error: package or namespace load failed for 'httpuv' in inDL(x, as.logical(local
), as.logical(now), ...):
 unable to load shared object 'C:/Documents and Settings/instrument/Desktop/Wlog
Book/packrat/lib/i386-w64-mingw32/3.5.0/httpuv/libs/i386/httpuv.dll':
  LoadLibrary failure:  The specified procedure could not be found.
```

And the pop-up from the first post.
Anything that can be done?

**Comment by wch** [comment]
I don't know for sure, but it sounds like something is wrong with the binary packages. Perhaps they were compiled for one version of R but you're trying to use them on a different version?

**Comment by stanstrup** [comment]
I compiled on windows 10 (32 bit R) and copied to XP.
In case that was the problem I have now tried to compile on XP. I get a popup saying:
"The procedure CancelSynchronousIo could not be located in the dynamic link library KERNEL32.dll"

**Comment by wch** [comment]
According to the [R for Windows FAQ]( https://cran.r-project.org/bin/windows/base/rw-FAQ.html#How-do-I-install-R-for-Windows_003f):

> Windows XP is no longer supported

Here's A thread from R-help with an error similar to the one you had: http://r.789695.n4.nabble.com/R-3-4-4-internet-access-fails-on-Windows-XP-td4749000.html

From that thread:

> R i386 runs without problems on Windows XP up to and including version 3.4.2.

**Comment by stanstrup** [comment]
I couldn't install from binary or source the latest version even on downgraded R. I still get the:
"The procedure entry point ConvertInterfaceIndexToLuid could not be located in the dynamic link library IPHLPAPI.DLL"

I could however install v1.3.5 fine so that will do.

**Comment by stanstrup** [comment]
Thanks. I did install Rtools 3.4. I wonder if compatibility was removed during 3.4.X so that to make Rtools works you need v3.3.

**Comment by wch** [comment]
Sorry, I just realized that I wasn't clear when I wrote that on my phone -- I meant "just one more possibility", not that it was the only possibility. :) You could be right that Rtools34 also lost XP, since it was not frozen until the last 3.4.x came out.
