### ISSUE TITLE
Get raw headers from request

### ISSUE THREAD

**Issue by alandipert** [rstudio/httpuv#141]
Currently, callback functions registered via `call` or `onHeaders` can only receive the "Rook-style" request headers ("HTTP_ Variables" in the [Rook README](https://github.com/jeffreyhorner/Rook)).

It would be useful if there was a way to receive the raw headers, before they were munged to become variable names, perhaps as a list of pairs of strings. That way, headers could be inspected without accounting for Rook's renaming of them.

Interested parties so far include @wch and @jeroen.

This capability raises various questions.

## Questions

1. What value should be used to represent raw headers?
    1. Shouldn't be an `env` because the same header might appear multiple times. This is valid in HTTP under [certain circumstances](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)
1. How should a handler be registered so that httpuv knows to pass it raw headers? And, how should that value be passed? Possibilities include:
    1. New `callRaw` and `onHeadersRaw` `app` members that pass the handler a second argument, the raw headers value. Using in conjunction with `call`/`onHeaders` respectively is an error.
    2. Always add the raw headers as an attribute of the Rook `req` object passed to `call`/`onHeaders`
        1. Problematic because attributes can contribute to object equality. Might not be backward-compatible?
        1. Introduces overhead we don't want to pay all the time?
    3. Add an `addRawRequest = TRUE` (default `FALSE`) member to `app`. This would be the only member of `app` so far that's not a function. Causes raw header value to be added to all `req`s as an attribute.
    4. Like above, but add the `addRawRequest = TRUE` optional argument to `startServer`/`startPipeServer` instead of as `app` member.
    5. Add `req$headers`
        1. Should this be an addition to Rook first, then httpuv?

**Comment by wch** [comment]
I think the most straightforward way to go is to use a named list, like `req$headers`, and to provide it unconditionally. Using a named list allows us to preserve the header order, and also to have multiple HTTP headers with the same name. This will be a feature of httpuv; we don't need to go change Rook.

@jeroen You had asked before for the "exact headers" from the request. Would a named list as described above be sufficient?

**Comment by alandipert** [comment]
@wch and I took a first cut at an implementation: https://github.com/rstudio/httpuv/commit/395d5684659d05b29af3f10cb393227276721ab5

It adds `HEADERS`, a named character vector, to the Rook request env.

We have some code that uses httpuv as a proxy frontend with a curl backend, and this change would simplify the conversion of Rook requests to parameterized curl handles.

@jeroen, would it suit your needs as well? We're curious to hear if it would work for you too, or if you otherwise have any feedback.
