### ISSUE TITLE
SIGPIPE on background thread can cause segfault

### ISSUE THREAD

**Issue by wch** [rstudio/httpuv#168]
Originally from trestletech/plumber#289. A SIGPIPE on the httpuv background thread can cause R to segfault.

**Comment by jcheng5** [comment]
What!? I could've sworn we sigignored it!

**Comment by jcheng5** [comment]
Need to ignore in later too

**Comment by wch** [comment]
We lost the `signal(SIGPIPE, SIG_IGN);` in the transition to httpuv on a background thread. I have a potential fix that blocks SIGPIPE only on the httpuv background thread, so that it doesn't interfere with other SIGPIPE stuff in R.

**Comment by jcheng5** [comment]
We used to ignore on the main thread, right? We might want to consider just sticking with that (or whatever it is that we used to do), I remember spending a lot of time and energy deciding on the right course of action there.

**Comment by wch** [comment]
We did used to ignore on the main thread, each time we were about to do a `uv_run()`:
  https://github.com/rstudio/httpuv/blob/v1.3.6/src/httpuv.cpp#L400-L404

However, R itself apparently does have a SIGPIPE handler and so I think it would be best not to mess with R's SIGPIPE handling if possible.

Somewhat related: https://github.com/s-u/Rserve/issues/100#issuecomment-371517836
