### ISSUE TITLE
Websocket Connection Issue with Shiny

### ISSUE THREAD

**Issue by jdonnell01** [rstudio/httpuv#190]
I am experiencing an issue with httpuv & Shiny where it seems that the websocket connection does not establish between the client and R. The app grays out and hangs when the user visits the site. In the console I see the errors:

- WebSocket connection to 'site' failed: Connection closed before receiving a handshake response
- Uncaught TypeError: Cannot read property 'readyState' of null

Any suggestions on how to remediate or debug?
Thank you

**Comment by wch** [comment]
Can you provide information about your system, and also the output of `sessioninfo::session_info()`? Are you using Shiny Server?
