### ISSUE TITLE
Suppress the error message "createTcpServer: address already in use"

### ISSUE THREAD

**Issue by yihui** [rstudio/httpuv#194]
Is there a way to suppress this error message? For example, it may show up when **shiny** looks for a random port: https://github.com/rstudio/shiny/blob/8ae31eb/R/server.R#L742 but the error message is not really useful to users.

**Comment by schloerke** [comment]
Reprex:

```r
srv1 <- httpuv::startServer("127.0.0.1", 12345, list())

errorMessage <- capture.output({
  tryCatch(
    {
      srv2 <- httpuv::startServer("127.0.0.1", 12345, list()) 
    }, 
    error = function(e) ""
  )
}, type = "message")
#> createTcpServer: address already in use
#> [1] ""
errorMessage
#> character(0)
```

`?capture.output`

> Messages sent to ‘stderr()’ (including those from ‘message’,
     ‘warning’ and ‘stop’) are captured by ‘type = "message"’.  Note
     that this can be “unsafe” and should only be used with care.

**Comment by wch** [comment]
I think the reason it can't be suppressed is because the message comes from a separate thread.
