### ISSUE TITLE
Upgrade Websocket api to RStudio/websocket?

### ISSUE THREAD

**Issue by vankesteren** [rstudio/httpuv#201]
Hi, 

is there a plan to upgrade the websocket api to the `RStudio/websocket` reasonably soon? I believe `httpuv` does not support `wss://` connections as is (please correct me if I'm wrong!)

**Comment by wch** [comment]
Sorry, we currently don't have plans to do this. wss is just the websocket protocol over an https connection, and we don't have plans to add https support.

(Also, the rstudio/websocket package is a websocket client, as opposed to httpuv, which can act as a websocket server. )
