### ISSUE TITLE
returning binary files from the 1.5.0 WebServer?

### ISSUE THREAD

**Issue by paul-shannon** [rstudio/httpuv#216]
My Bioconductor package igvR, built on BrowserViz - recently updated to use httpuv 1.5.0 - needs to return a binary file to ````igv.js```` running in the browser.   In the current case, this a genomic BAM (binary alignment map) file.   

The httpuv WebServer nicely supports returning other genomic ````text```` files used by igv:  bed, vcf, bedGraph.  Can it return a binary file over http also?

FWIW, BrowserViz detects and responds to file requests using a technique I developed (probably borrowed from example code) with httpuv 1.3.x.   Maybe it is antiquated, needs updating, and in updating I'd get binary file support?    Here's how I currently do it:
````
   wsCon$call = function(req) {
      qs <- req$QUERY_STRING
      if(nchar(qs) > 0){
         queryProcessorFunction <- BrowserViz.state[["httpQueryProcessingFunction"]]
         if(!is.null(queryProcessorFunction))
           body <- queryProcessorFunction(qs)
         else
           body <- "no query processor registered"
         return(list(status=200L, headers = list('Content-Type' = 'text/html'),
                     body=body))
         } # the request had a query string
````
Advice eagerly accepted!

**Comment by jcheng5** [comment]
You should just be able to use a raw vector in place of the string, for the `body`. Here's the relevant section of the Rook spec: https://github.com/jeffreyhorner/Rook/blob/master/README.md#the-body

**Comment by paul-shannon** [comment]
Thanks for the pointer @jcheng5.  I'll get a better understanding of Rook.

**Comment by wch** [comment]
I think you also need to use a different `Content-Type`:

```
   headers = list('Content-Type' = 'application/octet-stream')
```

**Comment by paul-shannon** [comment]
Seems obvious now that you pointed that out!  Thank you.
