### ISSUE TITLE
Errors with https://localhost

### ISSUE THREAD

**Issue by Hong-Revo** [rstudio/httpuv#217]
Hi, are there any known problems with using httpuv to listen on https://localhost, as opposed to http?

The background is that we're trying to enable Azure B2C authentication [here](https://github.com/cloudyr/AzureAuth/issues/11) and running into problems with the redirect URI. It keeps erroring out with what seems to be a TLS issue:

![image](https://user-images.githubusercontent.com/11328890/57027661-59d11880-6c80-11e9-8876-04c1172d3485.png)
(MS Edge screenshot)

It's a https redirect because of Azure policy.

**Comment by wch** [comment]
Sorry, httpuv currently doesn't support https.
