### ISSUE TITLE
httpuv installation error require no space between '-L' and '/usr/local/curl/lib'

### ISSUE THREAD

**Issue by pagarwal14** [rstudio/httpuv#252]
I am installation Seurat 3 from cran and part of the installation is Shiny.  When installing Shiny the dependency httpuv needs to be installed which is giving an error.
Platform: RHEL 6
R version 3.5.2

sudo R CMD INSTALL /srv/agarw005/installs/R_Packages_112619/httpuv
libtool:   error: require no space between '-L' and '/usr/local/curl/lib'
make[1]: *** [libuv.la] Error 1
make[1]: Leaving directory `/srv/agarw005/installs/R_Packages_112619/httpuv/src/libuv'
make: *** [libuv/.libs/libuv.a] Error 2
ERROR: compilation failed for package ‘httpuv’
* removing ‘/GenomicPrimaryData/installs/R/R-3.5.2/lib64/R/library/httpuv’

Prior to using this command I had installed the latest version of curl and used that for the installation of packages.
export LD_LIBRARY_PATH=/srv/agarw005/installs/curl/libcurl/lib/:$LD_LIBRARY_PATH

If I try to install from within R I get the same error.
From within R this is what I get for the env var:

> Sys.getenv("LD_LIBRARY_PATH")
[1] "/GenomicPrimaryData/installs/R/R-3.5.2/lib64/R/lib:/usr/local/pcre/lib:/usr/local/xz/lib::/usr/local/zlib/lib:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el6_10.x86_64/jre/lib/amd64/server:/srv/agarw005/installs/curl/libcurl/lib/:/opt/rh/devtoolset-3/root/usr/lib64:/opt/rh/devtoolset-3/root/usr/lib"

I cannot even see 
'/usr/local/curl/lib'
but perhaps this is in default?

I have used this same set of commands to install many R packages from command line or from within R without any problem.  Only the Shiny package (httpuv) specifically is giving this problem.

Thanks for your help.
- Pankaj

**Comment by wch** [comment]
The string `/usr/local/curl/lib` doesn't appear in the sources for httpuv. It's likely you have some local configuration that is pointing there.

**Comment by pagarwal14** [comment]
Can you provide any information on how I can find if there is a local configuration and how to remedy this.  As I mentioned I installed many packages using the exact same set of commands, so this seems something unique to Shiny and httpuv.

**Comment by wch** [comment]
I suggest checking your R installation's Makeconf file, as well as your `~/.R/Makevars` file, if it exists.

Also, I believe that the `LD_LIBRARY_PATH` is for dynamically-linked libraries (.so files), whereas the `-L` flag is used for static linking (.a files).

**Comment by pagarwal14** [comment]
What should I check for in the R installation's Makeconf file.
Can you please provide some details in your answers.  Such high level responses are not very helpful since I am not an expert Linux sys admin.
Thanks.

**Comment by wch** [comment]
I found a similar issue in a completely different project, where `LDFLAGS` was set and causing problems. https://github.com/JuliaLang/julia/issues/13788

Please note that this issue tracker is meant for bug reports and feature requests; it isn't a general support forum. If you want more detailed help, please use https://community.rstudio.com/ or https://stackoverflow.com/.
