### ISSUE TITLE
./config.guess: unable to guess system type

### ISSUE THREAD

**Issue by MajorDaxx** [rstudio/httpuv#255]
I use a CentOS7 Docker image which is harden from my company.
Im able to install libuv via 'yum install libuv' 

But if i install httpuv i get the following error:

(cd libuv \
        && touch aclocal.m4 \
        && touch -r aclocal.m4 configure Makefile.in \
        && chmod +x configure \
        && CC="gcc -m64 -std=gnu99" CFLAGS="-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -fpic -fvisibility=hidden" AR="ar" RANLIB="ranlib" LDFLAGS="-Wl,-z,relro " ./configure "--quiet")
./config.guess: unable to guess system type

This script (version 2018-03-08), has failed to recognize the
operating system you are using. If your script is old, overwrite *all*
copies of config.guess and config.sub with the latest versions from:

  https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess
and
  https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub

If ./config.guess has already been updated, send the following data and any
information you think might be pertinent to config-patches@gnu.org to
provide the necessary information to handle your system.

config.guess timestamp = 2018-03-08

uname -m = GameBoy Color
uname -r = GameBoy Color
uname -s = GameBoy Color
uname -v = GameBoy Color

/usr/bin/uname -p = GameBoy Color
/bin/uname -X     = GameBoy Color

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = x86_64
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = "GameBoy Color"
UNAME_RELEASE = "GameBoy Color"
UNAME_SYSTEM  = "GameBoy Color"
UNAME_VERSION = "GameBoy Color"
configure: error: cannot guess build type; you must specify one
make: *** [libuv/Makefile] Error 1
ERROR: compilation failed for package 'httpuv'
* removing '/usr/lib64/R/library/httpuv'

Is it anyhow possible to use the allredy installed libuv insted the on from httpuv
Or did i somthing totaly wrong?

**Comment by wch** [comment]
Sorry, there currently isn't a way to use the system's libuv. I've created a branch of httpuv with an updated version of libuv though. Can you try installing with:


```R
remotes::install_github('rstudio/httpuv@update-libuv')
```

**Comment by MajorDaxx** [comment]
Thanks for your quick answer. Sadly it didnt work :( 
Same issue as before.

**Comment by MajorDaxx** [comment]
Thanks a lot for your quick answer. The mistake was caused by the docker base image. So it was not httpuv failure.
