### ISSUE TITLE
Publish new version (1.5.3?) to CRAN

### ISSUE THREAD

**Issue by LHaferkamp** [rstudio/httpuv#261]
The [latest version on CRAN](https://cran.r-project.org/web/packages/httpuv/index.html) is 1.5.2 and already 6 month old. Meanwhile there were a lot of improvements and bug fixes here, also one I submitted and I'm waiting for before I can remove my workaround.
Could the maintainers of this package please publish a new version to CRAN?
I would also help in some tasks if anything needed before publishing

**Comment by wch** [comment]
We'll probably be releasing a new version in about a month.

**Comment by marco27384** [comment]
Hi @wch It's been more than a month since you mentioned you'd be releasing a new version. Any updates? Would be handy so I can remove my fork and workaround. Thanks

**Comment by wch** [comment]
@marco27384 Sorry, we've had some unexpected delays, but we do still plan to release in the next 2 weeks.

**Comment by marco27384** [comment]
Thank you @wch appreciate your efforts.
