### ISSUE TITLE
Installation fails on x86_64-linux-musl (with solution)

### ISSUE THREAD

**Issue by skratkk** [rstudio/httpuv#285]
Installation fails on x86_64-linux-musl:

     term[~/Downloads]$ sudo R CMD INSTALL httpuv/
    * installing to library '/usr/lib/R/library'
    * installing *source* package 'httpuv' ...
    file 'src/Makevars' has the wrong MD5 checksum
    ** using staged installation
    ** libs
    make: 'httpuv.so' is up to date.
    installing to /usr/lib/R/library/00LOCK-httpuv/00new/httpuv/libs
    ** R
    ** demo
    ** byte-compile and prepare package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** testing if installed package can be loaded from temporary location
    Error: package or namespace load failed for 'httpuv' in dyn.load(file, DLLpath = DLLpath, ...):
    unable to load shared object '/usr/lib/R/library/00LOCK-httpuv/00new/httpuv/libs/httpuv.so':
    Error relocating /usr/lib/R/library/00LOCK-httpuv/00new/httpuv/libs/httpuv.so: backtrace: symbol not found
    Error: loading failed
    Execution halted
    ERROR: loading failed
    * removing '/usr/lib/R/library/httpuv'
    * restoring previous '/usr/lib/R/library/httpuv'

Under x86_64-linux-musl the function `backtrace` is contained in library `/usr/lib/libexecinfo.so`, so it is sufficient to link that:

    term[~/Downloads]$ cd httpuv/src/
    term[~/Downloads/httpuv/src]$ g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -o httpuv.so RcppExports-legacy.o RcppExports.o callback.o callbackqueue.o filedatasource-unix.o filedatasource-win.o fs.o http.o httprequest.o httpresponse.o httpuv.o md5.o mime.o set_invalid_parameter.o socket.o staticpath.o thread.o utils.o uvutil.o webapplication.o websockets-base.o websockets-hixie76.o websockets-hybi03.o websockets-ietf.o websockets.o winutils.o ./libuv/.libs/libuv.a ./http-parser/http_parser.o ./sha1/sha1.o ./base64/base64.o -pthread -L/usr/lib64/R/lib -lR -lexecinfo
    term[~/Downloads/httpuv/src]$ cd ../..
    term[~/Downloads]$ sudo R CMD INSTALL httpuv/
    * installing to library ‘/usr/lib/R/library’
    * installing *source* package ‘httpuv’ ...
    file ‘src/Makevars’ has the wrong MD5 checksum
    ** using staged installation
    ** libs
    make: 'httpuv.so' is up to date.
    installing to /usr/lib/R/library/00LOCK-httpuv/00new/httpuv/libs
    ** R
    ** demo
    ** byte-compile and prepare package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** testing if installed package can be loaded from temporary location
    ** checking absolute paths in shared objects and dynamic libraries
    ** testing if installed package can be loaded from final location
    ** testing if installed package keeps a record of temporary installation path
    * DONE (httpuv)

Therefore, I found it is sufficient to modify the Makevars file, adding `-lexecinfo` at the end of the `PKG_LIBS` definition:

    PKG_LIBS = ./libuv/.libs/libuv.a ./http-parser/http_parser.o ./sha1/sha1.o ./base64/base64.o  -pthread -lexecinfo

**Comment by wch** [comment]
Related to https://github.com/r-lib/later/issues/135. Similar to my comment there, adding `-lexecinfo` will break things on other platforms.

**Comment by wch** [comment]
Closing, because this is an issue with Rcpp and musl, and the Rcpp maintainers have a solution for it.
https://github.com/r-lib/later/issues/135#issuecomment-692146847
