### ISSUE TITLE
move handler code from shiny to this library

### ISSUE THREAD

**Issue by hcorrada** [rstudio/httpuv#33]
It would be great to have the awesome 'middleware.R' code in shiny as part of httpuv:
https://github.com/rstudio/shiny/blob/master/R/middleware.R

**Comment by thomasp85** [comment]
@jcheng5 - I have begun to write a new package for a more general web server abstraction in R - Currently at a very early stage at [thomasp85/fiery](https://github.com/thomasp85/fiery). Would you be willing to discuss some of your experiences and how you would redo the middleware code?

**Comment by jcheng5** [comment]
The middleware stuff is really low level, like Rack, Servlet API, or WSGI level. I would make a layer on top that's opinionated and user-focused, and has built-in support for routing, REST idioms, and parameter matching--not just implemented as decorators.

I'd also rethink the API for request/response objects. As they are now they're just following the Rook specification and one could imagine a nicer API for manipulating them.

**Comment by thomasp85** [comment]
Thanks for responding @jcheng5. The whole point of my project is exactly to create a user-focused layer that abstracts all this away. It is a pass-time project though, and my experience with creating server frameworks is low atm. Would you be interested in commenting on ideas and implementations from time to time so some of your experiences will get incorporated?

**Comment by jcheng5** [comment]
@thomasp85 While I'd certainly be willing to weigh in, I'd advise you to set your expectations pretty low--I'm stretched a little thin these days and it can be hard for me to find time to provide answers to questions not directly related to the projects I'm working on. Definitely feel free to ask away though!

**Comment by thomasp85** [comment]
@jcheng5 Thats all I was expecting/hoping - thanks
