### ISSUE TITLE
`encodeURI()` incorrectly encodes newline characters

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/httpuv#336]
From [the encodeURI page on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI), we expect `"\n"` to be encoded as `"%0A"`, but `httpuv::encodeURI()` returns the wrong value.

``` r
httpuv::encodeURI("\n")
#> [1] "% A"

charToRaw(httpuv::encodeURIComponent("\n"))
#> [1] 25 20 41

charToRaw("%0A")
#> [1] 25 30 41

v8 <- V8::new_context()
v8$eval("decodeURI('%0A')")
#> [1] "\n"
```

Oddly, using V8 to evaluate `encodeUIR("\n")` results in an unspecified c++ exception

```r
v8$eval("encodeURI('\n')")
#> Error in context_eval(join(src), private$context, serialize) : 
#>   c++ exception (unknown reason)
```

**Comment by wch** [comment]
It looks like it's putting a leading space instead of a `0`. 

```R
httpuv::encodeURI("\n")
#> [1] "% A"
httpuv::encodeURI("\r")
#> [1] "% D"
httpuv::encodeURI("\f")
#> [1] "% C"
```
