### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by jim-sheldon** [rstudio/httpuv#350]
Hello,

Does this library support [HTTP/2](https://datatracker.ietf.org/doc/html/rfc7540), or are there plans to support it?

Thanks in advance!

**Comment by jcheng5** [comment]
No, and there are currently no plans to implement it, sorry. The best I can suggest is to run an HTTP/2 proxy in front of httpuv (the vast majority of production usage puts httpuv behind at least one proxy anyway). If this is a problem for you we'd love to hear about your scenario!

**Comment by jim-sheldon** [comment]
Lack of HTTP/2 support in R means no native R gRPC client or server, which we need to to distributed analytics/federated ML with R scripts. Our unfortunate solution: porting any desired R scripts to another language.
