### ISSUE TITLE
Unable to install httput - R 4.2.2

### ISSUE THREAD

**Issue by TylerSagendorf** [rstudio/httpuv#353]
Attempting to run R-CMD-check GitHub workflow results in this error:
```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'httpuv'
```

I get the following warning when trying to update the package on my computer (R 4.2.2):
```
package ‘httput’ is not available for this version of R
```

**Comment by TylerSagendorf** [comment]
Specifically fails on Windows, but not Mac.

**Comment by jcheng5** [comment]
I think you have just a typo there: "httput"

**Comment by TylerSagendorf** [comment]
It was spelled correctly in the error message from the R-CMD-check GitHub action:

```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'httpuv'
```

So that wasn't the cause. The error seems to have resolved itself, thankfully, as I have not encountered it since.
