### ISSUE TITLE
Possible to use multiple worker threads?

### ISSUE THREAD

**Issue by dansmith01** [rstudio/httpuv#358]
Does httpuv have the ability to use more than one worker thread at once?

This question was asked five years ago in issue #105, and the answer then was to use the future package and promises to wrap httpuv calls. 

Here's a minimal server example that waits for the number of seconds given in the url.
```
x <- httpuv::startServer(
  host = "0.0.0.0", 
  port = 8080,
  app  = list(call = function(req) {
    
    stopifnot(grepl("^/\\d+$", req[['PATH_INFO']]))
    seconds <- as.integer(sub("/", "", req[['PATH_INFO']]))
    
    t1 <- as.character(Sys.time())
    Sys.sleep(seconds)
    t2 <- as.character(Sys.time())
    
    return (list(
      status  = 200L,
      headers = list('Content-Type' = 'text/plain'),
      body    = sprintf("slept for %i seconds\n%s\n%s", seconds, t1, t2) ))
}))
```

If you visit `localhost:8080/3` it will load for 3 seconds then give you some output. Same for `localhost:8080/20` and 20 seconds. But if you visit `localhost:8080/3` while `localhost:8080/20` is loading it'll take much longer than 3 seconds to complete. It's apparent that the tasks are being executed sequentially rather than in parallel on the back end.

Is the future/promise approach still the best practice for parallel processing simultaneous http requests?

**Comment by dansmith01** [comment]
For other people's reference (and my own), here's the same code, but returning a promise from the future package to enable running non-blocking background R worker threads in parallel:

```R
future::plan(future::multisession)

x <- httpuv::startServer(
  host = "0.0.0.0", 
  port = 80,
  app  = list(call = function(req) {
    
    stopifnot(grepl("^/\\d+$", req[['PATH_INFO']]))
    seconds <- as.integer(sub("/", "", req[['PATH_INFO']]))
    
    t1 <- as.character(Sys.time())
    
    promises::as.promise(
      future::future({
    
        Sys.sleep(seconds)
        t2 <- as.character(Sys.time())
        
        list(
          status  = 200L,
          headers = list('Content-Type' = 'text/plain'),
          body    = sprintf("slept for %i seconds\n%s\n%s", seconds, t1, t2) )
      }))
}))
```

Credit to user [seasick](https://stackoverflow.com/users/1706846/seasick) for his post on [stackoverflow](https://stackoverflow.com/a/73404824).

**Comment by jcheng5** [comment]
For requests that are handled by R code, there's no way to use threads, as the R interpreter is single-threaded. Using {future} to spawn an R subprocess as you've done in your example is the closest thing there is.

The only requests httpuv can handle on a separate thread are for static assets using the [static paths feature](https://github.com/rstudio/httpuv#static-paths), as those are handled on a background C++ thread.
