### ISSUE TITLE
macOS: Assertion fails when closing `{httpuv}` server

### ISSUE THREAD

**Issue by schloerke** [rstudio/httpuv#362]
Example: https://github.com/rstudio/httpuv/actions/runs/4911951339/jobs/8770464750#step:4:152

Probable failing assertion: https://github.com/rstudio/httpuv/blob/faada3a19965af80289919308587836d22198a24/src/libuv/src/unix/core.c#L259

Reprex: Start shiny app then close app. Error is thrown and R session is killed

cc @gadenbuie

**Comment by gadenbuie** [comment]
Here's the log from installing from source on my Mac M1 with R 4.3: https://gist.github.com/gadenbuie/5e7c103f9b35189f9a657ab47603fc90

**Comment by jcheng5** [comment]
Fixed in 1.6.11
