### ISSUE TITLE
install.packages on Ubuntu 14.10 fails (while install_github works)

### ISSUE THREAD

**Issue by fnl** [rstudio/httpuv#40]
Ubuntu: 14.10
RStudio: 0.98.1087
gcc: 4.9.1

When installing via `install.packages("httpuv")` I get the following problem:

```
[snip]
g++ -shared -Wl,-Bsymbolic-functions -Wl,-z,relro -o httpuv.so RcppExports.o filedatasource-unix.o filedatasource-win.o http.o httpuv.o md5.o set_invalid_parameter.o uvutil.o websockets-base.o websockets-hixie76.o websockets-hybi03.o websockets-ietf.o websockets.o Started R session at Tue Dec 23 15:22:24 2014 Closing R session at Tue Dec 23 15:22:24 2014 ./libuv/libuv.a ./http-parser/http_parser.o ./sha1/sha1.o ./base64/base64.o -L/usr/lib/R/lib -lR
g++: error: Started: No such file or directory
g++: error: R: No such file or directory
g++: error: session: No such file or directory
g++: error: at: No such file or directory
g++: error: Tue: No such file or directory
[/snip]
```

If I install `httpuv` using `devtools::install_github('httpuv', 'rstudio')` instead, the package installs just nicely.
No idea how this "Started R session at ..." line slips in, however.

**Comment by fnl** [comment]
While working with another package, I finally found the culprit... I had ``.First()`` and ``.Last()`` functions in my `.Rprofile` that would write those strings via `cat("\nStarted R session at ", date(), "\n")`... Somehow, these two cats then broke my compilation processes... Phew :)

After removing that stuff from my profile, my packages compile fine again (inlcuding httpuv).

**Comment by siddiqui16** [comment]
I experienced exactly the same issue. 
.First() & .Last() in Rprofile.site were also cat(ing) to the console. After their removal httpuv installed fine.
