### ISSUE TITLE
Error on attaching

### ISSUE THREAD

**Issue by Helmut01** [rstudio/httpuv#400]
`library(httpuv) # 1.6.15 (2024-03-26)`  
I got…  
![Zwischenablage01](https://github.com/user-attachments/assets/020bfcc9-9753-408e-8f4f-02800a9b53e8)  
… and then  
`Error: package or namespace load failed for ‘httpuv’ in inDL(x, as.logical(local), as.logical(now), ...):`
` unable to load shared object 'D:/Program Files/R/R-4.4.1/library/httpuv/libs/x64/httpuv.dll':`
`  LoadLibrary failure:  Die angegebene Prozedur wurde nicht gefunden.`  

`sessionInfo()`
`R version 4.4.1 (2024-06-14 ucrt)`
`Platform: x86_64-w64-mingw32/x64`
`Running under: Windows 7 x64 (build 7601) Service Pack 1`
`Matrix products: default`
`locale:`
`[1] LC_COLLATE=German_Austria.1252  LC_CTYPE=German_Austria.1252`
`[3] LC_MONETARY=German_Austria.1252 LC_NUMERIC=C`         
`[5] LC_TIME=German_Austria.1252`
`time zone: Europe/Vienna`
`tzcode source: internal`
`attached base packages:`
`[1] stats     graphics  grDevices utils     datasets  methods   base`
`other attached packages:`
`[1] usethis_2.2.3`
`loaded via a namespace (and not attached):`
` [1] digest_0.6.36     later_1.3.2       R6_2.5.1          fastmap_1.2.0`
` [5] magrittr_2.0.3    cachem_1.1.0      glue_1.7.0        htmltools_0.5.8.1`
` [9] memoise_2.0.1     lifecycle_1.0.4   promises_1.3.0    cli_3.6.3`      
`[13] vctrs_0.6.5       compiler_4.4.0    purrr_1.0.2       tools_4.4.0`  
`[17] ellipsis_0.3.2    Rcpp_1.0.12       rlang_1.1.4       fs_1.6.4`

I have also the current version of `devtools` (2022-10-11) installed.

**Comment by jcheng5** [comment]
I wonder if it’s because you’re running Windows 7. Do you have the ability to build packages from source? If so, maybe try that: `install.packages("httpuv", type="source")`

**Comment by Helmut01** [comment]
I removed the library and installed the latest version from CRAN. Yes, I can. I have RBuildTools 4.0 and all paths correctly set. However:  
`install.packages("httpuv", type="source")`
`trying URL 'https://cloud.r-project.org/src/contrib/httpuv_1.6.15.tar.gz'`
`Content type 'application/x-gzip' length 1879369 bytes (1.8 MB)`
`downloaded 1.8 MB`

`Welcome at Fri Jul 19 10:12:11 2024`
`* installing *source* package 'httpuv' ...`
`** package 'httpuv' successfully unpacked and MD5 sums checked`
`** using staged installation`

`   **********************************************`
`   WARNING: this package has a configure script`
`         It probably needs manual configuration`
`   **********************************************`

`** libs`
`Error in system(paste(MAKE, p1(paste("-f", shQuote(makefiles))), "compilers"),  :`
`  'make' not found`
`* removing 'D:/Program Files/R/R-4.4.1/library/httpuv'`
`* restoring previous 'D:/Program Files/R/R-4.4.1/library/httpuv'`

`The downloaded source packages are in`
`        ‘C:\Users\BEBAC\AppData\Local\Temp\Rtmpo5aCMf\downloaded_packages’`
`Warning message:`
`In install.packages("httpuv", type = "source") :`
`  installation of package ‘httpuv’ had non-zero exit status`

**Comment by jcheng5** [comment]
It sure seems like `make` should be found if you set your path correctly. It’s used in the docs as an example of how to verify your path is set correctly. https://cran.rstudio.com/bin/windows/Rtools/rtools40.html

**Comment by Helmut01** [comment]
Old toolchain, updated to RTools4.4  
`Sys.which("make")`
`                              make`
`"C:\\rtools44\\usr\\bin\\make.exe`

THX for helping me and sorry for the confusion caused. Case closed.

**Comment by jcheng5** [comment]
Glad you were able to figure it out!

I suspect the reason you need to build from source is because CRAN binaries are compiled against a newer version of Windows—it looks like they use Windows Server 2022.

> We primarily test on versions of Windows currently supported by Microsoft, recently mainly Windows 10, Windows Server 2022 and sometimes on Windows 11. The most thorough testing is done via CRAN packages checks: for R 4.3-4.4 this has been on Windows Server 2022. R 4.3-4.4.0 has been tested to install, start and pass its own checks also on Windows 7 and Windows 8.1, but it has not been tested with contributed packages.

https://cran.r-project.org/bin/windows/base/rw-FAQ.html
