### ISSUE TITLE
ERROR: compilation failed for package ‘httpuv’ <zlib.h>

### ISSUE THREAD

**Issue by vinferrer** [rstudio/httpuv#402]
While installing httpuv this error appeared:
```
In file included from gzipdatasource.cpp:1:
gzipdatasource.h:4:10: fatal error: zlib.h: No such file or directory
    4 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:200: gzipdatasource.o] Error 1
ERROR: compilation failed for package ‘httpuv’
* removing ‘/home/vicente/R/httpuv’
Warning in install.packages :
  installation of package ‘httpuv’ had non-zero exit status

```

Enviroment:
Ubuntu 24.02
R 4.3.3
Rstudio 2024.09.0 Build 375
 zlib1g-dev installed, previous version  zlib-dev not available

**Comment by wch** [comment]
Do you have `/usr/include/zlib.h` on your computer?

According to this file list it should be there:
https://packages.ubuntu.com/focal/amd64/zlib1g-dev/filelist

**Comment by vinferrer** [comment]
Hello @wch,
Thank you for offering help.
Answering to your question. Yes I do have `/usr/include/zlib.h` in my computer and still the error appears.
I was trying to install httpuv for devtools, but I manage to install devtools using `apt install r-cran-devtools`.
My problem is solved so unless you think this could happen to other people, we can close this issue.
