### ISSUE TITLE
Upcoming support for R as websocket client?

### ISSUE THREAD

**Issue by jeromefroe** [rstudio/httpuv#52]
Hello, I was just curious if there were any plans to include support for using R as a Websocket client in the future? I'm interested in being able to stream data from a server using javascript (e.g. socket.io, or sockjs) and listen to the data in R, from which I can build a shiny app to visualize or analyze the data in real time, similar to the [CRAN packages app](https://github.com/rstudio/shiny-examples/tree/master/087-crandash). Thanks!

**Comment by jadaliha** [comment]
is there any news in adding this in close future?
I need to connect R as a websocket client to another R as websocket server (on two different computer).

**Comment by MattSandy** [comment]
It definitely can act as a websocket server (which sounds like what you are actually wanting). I have a pending pull request which demos that functionality https://github.com/MattSandy/httpuv/blob/f4621f7ad0da419c52e51cd84d5d350582a9bc2e/demo/json-server.R #95

**Comment by jadaliha** [comment]
Actually, I'm looking to connect to a WebSocket server from R, so R should be a client.

**Comment by MattSandy** [comment]
Sorry about that. I was going off what @jeromefroe was requesting. Stumbled across this old thread while looking for a websocket client library myself.

**Comment by MattSandy** [comment]
If you haven't found anything yet, I made a very simple command line utility to send websocket messages https://github.com/MattSandy/wspr and some smarter people than me have been able to use netcat.

**Comment by wch** [comment]
We've been working on a separate WebSocket client package here:
https://github.com/rstudio/websocket
