### ISSUE TITLE
Non-zero exit status due to .Last and/or message in .Rprofile

### ISSUE THREAD

**Issue by chendaniely** [rstudio/httpuv#54]
I could not find the reason for httpuv not being able to install (as a dependency for shiny), but deleting my `.Rprofile` seemed to solve the problem.

contents of `.Rprofile`:

``` R
q <- function (save="no", ...) {
  quit(save=save, ...)
}

.First <- function(){
 cat("\nWelcome at", date(), "\n")
}

.Last <- function(){
 cat("\nGoodbye at ", date(), "\n")
}

message("\n*** Successfully loaded .Rprofile ***\n")
```

Could this be from me re-defining `.Last` or having my own `message` in my `.Rprofile`?  Seems like there's a last message check in `daemon-echo.R`

This might be more of a reference for people who people in installation issues.

**Comment by wch** [comment]
If I remember correctly, messages that are printed out in `.Rprofile` can cause problems with `R CMD install`.

If you're willing to have it print out those messages only in interactive seesions, you can wrap them in `if (interactive()) { ... }`.
