### ISSUE TITLE
Can't set multiple headers of the same name

### ISSUE THREAD

**Issue by trestletech** [rstudio/httpuv#59]
I can't find a way to set multiple headers of the same name on a single response. Since the headers are kept in a list, I think it's impossible to set multiple cookies in a single response.

e.g. 
```
Set-Cookie a=1;
Set-Cookie b=2;
```

would not be possible at the moment.

**Comment by jcheng5** [comment]
Are you sure? `list("Set-Cookie" = "a=1;", "Set-Cookie" = "b=2;")` is totally valid from an R perspective (though I haven't tried it with httpuv).

**Comment by jcheng5** [comment]
Or dynamically:

```r
headers <- list()
headers <- c(headers, list("Set-Cookie" = "a=1;"))
headers <- c(headers, list("Set-Cookie" = "a=2;"))
```

**Comment by trestletech** [comment]
Oh interesting. I'll try those now.

**Comment by trestletech** [comment]
Muh bad. Thanks for the tip.

**Comment by jcheng5** [comment]
OK great!
