### ISSUE TITLE
Listen to all http requests coming from an R session?

### ISSUE THREAD

**Issue by sckott** [rstudio/httpuv#60]
Any way to do this?  Hoping to listen to any http request made by a user and gather their results (headers, url, body, etc.)

**Comment by jcheng5** [comment]
You want to intercept and inspect the http requests coming out of an R process, no matter what code originated them or what host they're going to?

**Comment by sckott** [comment]
Yeah, its the same concept as this chrome plugin https://chrome.google.com/webstore/detail/live-http-headers/iaiioopjkcekapmldfgbebdclcnpgnlo  - trying to make a shiny app that will listen via httpuv for http requests and display them so users can inspect all their requests - not sure if this is possible though. 

The use case is that I want a viewer for https://github.com/ropenscilabs/vcr users to inspect all their http requests via files on the file system that define http request and response fields . This is straightforward. 

However,  I thought to make it more general it would be nice to optionally listen for all http requests made from R (or some subset defined by the user, either port or host specific, etc.)  - this is the hard part

**Comment by sckott** [comment]
@jcheng5 any thoughts on this?  i'm also trying to port the Ruby library https://github.com/bblimke/webmock - which takes the approach of listening to http request made in the ruby session - would be interested to know if you think this is doable

**Comment by wch** [comment]
Closing because this is out of scope for httpuv.

**Comment by sckott** [comment]
sounds good, figured out the right (and different) approach
