### ISSUE TITLE
change std::auto_ptr: it's deprecated

### ISSUE THREAD

**Issue by mpadge** [rstudio/httpuv#77]
Installing/upgrading `httpuv` fails with clang compiler because
```
websockets.cpp:217:8: warning: ‘template<class> class std::auto_ptr’ is deprecated
std::auto_ptr<WebSocketProto_IETF> ietf(new WebSocketProto_IETF());    
```
also on `websockets.cpp` line#223, with corresponding declaration in `websockets.h` line#49. Easy to work around, but perhaps you guys had better fix that.

**Comment by jcheng5** [comment]
Fixed, thank you!
