### ISSUE TITLE
Build Fails with unrecognized command line option "-std=c++11" (RHEL6.7, R 3.3.3)

### ISSUE THREAD

**Issue by jfrabetti** [rstudio/httpuv#84]
I am working on a Jenkins build and it fails with the httpuv installation:
g++ -std=c++11 -I/etc/etc/R/lib64/R/include -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I/usr/local/include -I"/etc/etc/Rcpp/include"   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘httpuv’
* removing ‘/etc/etc/etc/httpuv’

We are working with an older version of Linux (understandably not optimal) and this is a compiler mismatch error, but I think the latest version of httpuv invokes that command line option...if so, can it be removed, please?

**Comment by jeroen** [comment]
This is a problem in your R configuration. You install R from EPEL install of building it yourself:

```
sudo yum install epel-release
sudo yum install R-devel
```

If you really want to build your own you need to fix the file `echo $(R RHOME)/etc/Makeconf`. What is your output for:

```
R CMD config CXX11
R CMD config CXX11FLAGS
```

Also the fact that your packages are being installed in `/etc/etc/etc/httpuv` makes me wonder if this is really the intended configuration of R.
