### ISSUE TITLE
Failing to build on macOS High Sierra, Xcode 9.0, R 3.4.2

### ISSUE THREAD

**Issue by JeffreyRacine** [rstudio/httpuv#89]
Greetings,

httpuv is failing to build and I have not recently had success... build log below in case that helps... thanks!

> install.packages("httpuv",repos="https://cran.wu.ac.at/")
Installing package into ‘/Users/jracine/Library/R’
(as ‘lib’ is unspecified)
trying URL 'https://cran.wu.ac.at/src/contrib/httpuv_1.3.5.tar.gz'
Content type 'application/x-gzip' length 427638 bytes (417 KB)
==================================================
downloaded 417 KB

* installing *source* package ‘httpuv’ ...
** package ‘httpuv’ successfully unpacked and MD5 sums checked
** libs
*** arch - x86_64
clang++ -arch x86_64 -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2 -c RcppExports.cpp -o RcppExports.o
clang++ -arch x86_64 -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2 -c filedatasource-unix.cpp -o filedatasource-unix.o
clang++ -arch x86_64 -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2 -c filedatasource-win.cpp -o filedatasource-win.o
clang++ -arch x86_64 -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2 -c http.cpp -o http.o
clang++ -arch x86_64 -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2 -c httpuv.cpp -o httpuv.o
clang -arch x86_64 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2  -c md5.c -o md5.o
clang -arch x86_64 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2  -c register.c -o register.o
clang -arch x86_64 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2  -c set_invalid_parameter.c -o set_invalid_parameter.o
clang++ -arch x86_64 -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2 -c uvutil.cpp -o uvutil.o
clang++ -arch x86_64 -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2 -c websockets-base.cpp -o websockets-base.o
clang++ -arch x86_64 -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2 -c websockets-hixie76.cpp -o websockets-hixie76.o
clang++ -arch x86_64 -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2 -c websockets-hybi03.cpp -o websockets-hybi03.o
clang++ -arch x86_64 -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2 -c websockets-ietf.cpp -o websockets-ietf.o
clang++ -arch x86_64 -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Resources/include/x86_64 -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/Users/jracine/Library/R/Rcpp/include" -I/opt/local/include   -fPIC  -g -O2 -c websockets.cpp -o websockets.o
make --directory=libuv \
		CC="clang -arch x86_64" CFLAGS="-g -O2  -fPIC" AR="ar" RANLIB="ranlib" \
    HAVE_DTRACE=0 \
		libuv.a
mkdir -p src/unix
touch src/unix/.buildstamp
clang -arch x86_64 --std=c89 -pedantic -Wall -Wextra -Wno-unused-parameter -I/opt/local/include -I/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpdmaPCF/R.INSTALL11753358f3cfa/httpuv/src/libuv/include -I/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpdmaPCF/R.INSTALL11753358f3cfa/httpuv/src/libuv/include/uv-private -I/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpdmaPCF/R.INSTALL11753358f3cfa/httpuv/src/libuv/src -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE=1 -Wno-deprecated-declarations -g -O2  -fPIC -c src/unix/async.c -o src/unix/async.o
In file included from src/unix/async.c:26:
In file included from src/unix/internal.h:25:
/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpdmaPCF/R.INSTALL11753358f3cfa/httpuv/src/libuv/src/uv-common.h:71:14: error:
      unknown type name 'uv_err_t'; did you mean 'uv_errno_t'?
extern const uv_err_t uv_ok_;
             ^~~~~~~~
             uv_errno_t
/opt/local/include/uv.h:179:3: note: 'uv_errno_t' declared here
} uv_errno_t;
  ^
In file included from src/unix/async.c:26:
In file included from src/unix/internal.h:25:
/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpdmaPCF/R.INSTALL11753358f3cfa/httpuv/src/libuv/src/uv-common.h:73:1: error:
      unknown type name 'uv_err_code'
uv_err_code uv_translate_sys_error(int sys_errno);
^
/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpdmaPCF/R.INSTALL11753358f3cfa/httpuv/src/libuv/src/uv-common.h:74:36: error:
      unknown type name 'uv_err_code'
int uv__set_error(uv_loop_t* loop, uv_err_code code, int sys_error);
                                   ^
/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpdmaPCF/R.INSTALL11753358f3cfa/httpuv/src/libuv/src/uv-common.h:76:47: error:
      unknown type name 'uv_err_code'
int uv__set_artificial_error(uv_loop_t* loop, uv_err_code code);
                                              ^
/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpdmaPCF/R.INSTALL11753358f3cfa/httpuv/src/libuv/src/uv-common.h:77:1: error:
      unknown type name 'uv_err_t'; did you mean 'uv_errno_t'?
uv_err_t uv__new_sys_error(int sys_error);
^~~~~~~~
uv_errno_t
/opt/local/include/uv.h:179:3: note: 'uv_errno_t' declared here
} uv_errno_t;
  ^
In file included from src/unix/async.c:26:
In file included from src/unix/internal.h:25:
/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpdmaPCF/R.INSTALL11753358f3cfa/httpuv/src/libuv/src/uv-common.h:78:1: error:
      unknown type name 'uv_err_t'; did you mean 'uv_errno_t'?
uv_err_t uv__new_artificial_error(uv_err_code code);
^~~~~~~~
uv_errno_t
/opt/local/include/uv.h:179:3: note: 'uv_errno_t' declared here
} uv_errno_t;
  ^
In file included from src/unix/async.c:26:
In file included from src/unix/internal.h:25:
/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpdmaPCF/R.INSTALL11753358f3cfa/httpuv/src/libuv/src/uv-common.h:78:35: error:
      unknown type name 'uv_err_code'
uv_err_t uv__new_artificial_error(uv_err_code code);
                                  ^
In file included from src/unix/async.c:26:
src/unix/internal.h:130:28: warning: declaration of 'struct uv__async' will not be visible outside of this
      function [-Wvisibility]
void uv__async_send(struct uv__async* wa);
                           ^
src/unix/internal.h:131:28: warning: declaration of 'struct uv__async' will not be visible outside of this
      function [-Wvisibility]
void uv__async_init(struct uv__async* wa);
                           ^
src/unix/internal.h:132:45: warning: declaration of 'struct uv__async' will not be visible outside of this
      function [-Wvisibility]
int uv__async_start(uv_loop_t* loop, struct uv__async* wa, uv__async_cb cb);
                                            ^
src/unix/internal.h:132:60: error: unknown type name 'uv__async_cb'; did you mean 'uv_async_cb'?
int uv__async_start(uv_loop_t* loop, struct uv__async* wa, uv__async_cb cb);
                                                           ^~~~~~~~~~~~
                                                           uv_async_cb
/opt/local/include/uv.h:306:16: note: 'uv_async_cb' declared here
typedef void (*uv_async_cb)(uv_async_t* handle);
               ^
In file included from src/unix/async.c:26:
src/unix/internal.h:133:45: warning: declaration of 'struct uv__async' will not be visible outside of this
      function [-Wvisibility]
void uv__async_stop(uv_loop_t* loop, struct uv__async* wa);
                                            ^
src/unix/internal.h:143:1: error: unknown type name 'uv_err_code'
uv_err_code uv_translate_sys_error(int sys_errno);
^
src/unix/internal.h:249:3: warning: implicit declaration of function 'ngx_queue_insert_tail'
      [-Wimplicit-function-declaration]
  uv__req_register(loop, req);
  ^
/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpdmaPCF/R.INSTALL11753358f3cfa/httpuv/src/libuv/src/uv-common.h:123:5: note:
      expanded from macro 'uv__req_register'
    ngx_queue_insert_tail(&(loop)->active_reqs, &(req)->active_queue);        \
    ^
src/unix/async.c:35:36: warning: declaration of 'struct uv__async' will not be visible outside of this
      function [-Wvisibility]
                            struct uv__async* w,
                                   ^
src/unix/async.c:42:36: error: no member named 'async_watcher' in 'struct uv_loop_s'; did you mean
      'async_io_watcher'?
  if (uv__async_start(loop, &loop->async_watcher, uv__async_event))
                                   ^~~~~~~~~~~~~
                                   async_io_watcher
/opt/local/include/uv.h:1497:3: note: 'async_io_watcher' declared here
  UV_LOOP_PRIVATE_FIELDS
  ^
/opt/local/include/uv-unix.h:211:12: note: expanded from macro 'UV_LOOP_PRIVATE_FIELDS'
  uv__io_t async_io_watcher;                                                  \
           ^
src/unix/async.c:58:35: error: no member named 'async_watcher' in 'struct uv_loop_s'; did you mean
      'async_io_watcher'?
    uv__async_send(&handle->loop->async_watcher);
                                  ^~~~~~~~~~~~~
                                  async_io_watcher
/opt/local/include/uv.h:1497:3: note: 'async_io_watcher' declared here
  UV_LOOP_PRIVATE_FIELDS
  ^
/opt/local/include/uv-unix.h:211:12: note: expanded from macro 'UV_LOOP_PRIVATE_FIELDS'
  uv__io_t async_io_watcher;                                                  \
           ^
src/unix/async.c:65:3: warning: implicit declaration of function 'ngx_queue_remove'
      [-Wimplicit-function-declaration]
  ngx_queue_remove(&handle->queue);
  ^
src/unix/async.c:71:36: warning: declaration of 'struct uv__async' will not be visible outside of this
      function [-Wvisibility]
                            struct uv__async* w,
                                   ^
src/unix/async.c:70:13: error: conflicting types for 'uv__async_event'
static void uv__async_event(uv_loop_t* loop,
            ^
src/unix/async.c:34:13: note: previous declaration is here
static void uv__async_event(uv_loop_t* loop,
            ^
src/unix/async.c:73:3: error: use of undeclared identifier 'ngx_queue_t'
  ngx_queue_t* q;
  ^
src/unix/async.c:73:16: error: use of undeclared identifier 'q'
  ngx_queue_t* q;
               ^
src/unix/async.c:76:3: warning: implicit declaration of function 'ngx_queue_foreach'
      [-Wimplicit-function-declaration]
  ngx_queue_foreach(q, &loop->async_handles) {
  ^
src/unix/async.c:76:21: error: use of undeclared identifier 'q'
  ngx_queue_foreach(q, &loop->async_handles) {
                    ^
src/unix/async.c:144:8: error: offsetof of incomplete type 'struct uv__async'
  wa = container_of(w, struct uv__async, io_watcher);
       ^               ~~~~~~
/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpdmaPCF/R.INSTALL11753358f3cfa/httpuv/src/libuv/src/uv-common.h:46:31: note:
      expanded from macro 'container_of'
  ((type *) ((char *) (ptr) - offsetof(type, member)))
                              ^        ~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/stddef.h:120:24: note:
      expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^                  ~
src/unix/async.c:117:10: note: forward declaration of 'struct uv__async'
  struct uv__async* wa;
         ^
src/unix/async.c:156:5: error: incomplete definition of type 'struct uv__async'
  wa->cb(loop, wa, n);
  ~~^
src/unix/async.c:117:10: note: forward declaration of 'struct uv__async'
  struct uv__async* wa;
         ^
src/unix/async.c:160:28: warning: declaration of 'struct uv__async' will not be visible outside of this
      function [-Wvisibility]
void uv__async_send(struct uv__async* wa) {
                           ^
src/unix/async.c:160:6: error: conflicting types for 'uv__async_send'
void uv__async_send(struct uv__async* wa) {
     ^
src/unix/internal.h:130:6: note: previous declaration is here
void uv__async_send(struct uv__async* wa);
     ^
src/unix/async.c:168:10: error: incomplete definition of type 'struct uv__async'
  fd = wa->wfd;
       ~~^
src/unix/async.c:160:28: note: forward declaration of 'struct uv__async'
void uv__async_send(struct uv__async* wa) {
                           ^
src/unix/async.c:194:28: warning: declaration of 'struct uv__async' will not be visible outside of this
      function [-Wvisibility]
void uv__async_init(struct uv__async* wa) {
                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
11 warnings and 20 errors generated.
make[1]: *** [src/unix/async.o] Error 1
make: *** [libuv.a] Error 2
ERROR: compilation failed for package ‘httpuv’
* removing ‘/Users/jracine/Library/R/httpuv’

The downloaded source packages are in
	‘/private/var/folders/dy/sbjj5q2s0qng776bmmqpcgvc0000gn/T/RtmpkDuQtC/downloaded_packages’
Warning message:
In install.packages("httpuv", repos = "https://cran.wu.ac.at/") :
  installation of package ‘httpuv’ had non-zero exit status
>

**Comment by wch** [comment]
I believe this should be fixed by #121. If it is still a problem, please re-open or file a new issue.
