### ISSUE TITLE
namespace 'httpuv' 1.3.3 is being loaded, but >= 1.3.5 is required

### ISSUE THREAD

**Issue by xinshuaiqi** [rstudio/httpuv#92]
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'httpuv' 1.3.3 is being loaded, but >= 1.3.5 is required

**Comment by xinshuaiqi** [comment]
> install.packages("httpuv")
Installing package into ‘C:/Users/qxs/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is
  later:
       binary source needs_compilation
httpuv  1.3.3  1.3.5              TRUE

  Binaries will be installed
trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.2/httpuv_1.3.3.zip'
Content type 'application/zip' length 872756 bytes (852 KB)
downloaded 852 KB

package ‘httpuv’ successfully unpacked and MD5 sums checked

**Comment by wch** [comment]
I think CRAN stops building binaries for older versions of R (3.3 is currently the earliest that they're building binaries for). You'll either need to install from source or upgrade R to a newer version.

Note that installing from source on Windows requires Rtools.

```R
install.packages("httpuv", type = "source")
```

**Comment by xinshuaiqi** [comment]
Solved after I update my R to the latest version. Thanks.
