### ISSUE TITLE
R hangs when using RCurl on daemonized server

### ISSUE THREAD

**Issue by bobjansen** [rstudio/httpuv#94]
If I do the following:

```
> wget https://raw.githubusercontent.com/rstudio/httpuv/master/demo/daemon-echo.R
> R
R> source("daemon-echo.R")
R> RCurl::getURL("http://localhost:9454/")
```
R hangs while `curl http://localhost:9454` from another terminal works. I'm on

```R
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.04

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=nl_NL.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=nl_NL.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=nl_NL.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=nl_NL.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] httpuv_1.3.5    roxygen2_6.0.1  devtools_1.13.2

loaded via a namespace (and not attached):
 [1] R6_2.2.1        magrittr_1.5    tools_3.3.2     withr_1.0.2
 [5] Rcpp_0.12.12    memoise_1.1.0   xml2_1.1.1      stringi_1.1.5
 [9] stringr_1.2.0   digest_0.6.12   packrat_0.4.8-1 commonmark_1.2
```
Is this reproducible? Using `RCurl` on other hosts or from another R session just works .

**Comment by jcheng5** [comment]
RCurl hangs when you use it to download _from_ a daemonized server running in the same session. This doesn't surprise me, as RCurl keeps the R session busy waiting for the response so R can't also be serving up the response at the same time. Note that while the daemonized server is running, you can still use RCurl to download from any other URL.

What is it you're trying to do?

**Comment by bobjansen** [comment]
I'm not familiar with the internals so it didn't immediately make sense to me but what you write makes sense.

I'm using `httpuv` as a webserver and wanted to write a test that starts the server and then tests the data fetched from this server using `RCurl`.

**Comment by bobjansen** [comment]
Hacked around it:

```R
source("daemon-echo.R")

nonBlockingGet <- function(url) {
  fileName <- tempfile()
  system2("curl", args = url, wait = FALSE, stdout = fileName, stderr = FALSE)

  fileSize <- file.info(fileName)[["size"]]
  while (is.na(fileSize) || fileSize == 0) {
    Sys.sleep(0.001)
    fileSize <- file.info(fileName)[["size"]]
  }

  readChar(fileName, file.info(fileName)[["size"]])
}

nonBlockingGet("http://localhost:9454/")
```

The loop takes about 8ms on my Linux machine, that's acceptable for testing. I didn't test on bigger files. The condition could be changed to checking for no file growth once `fileSize > 0`.

**Comment by jcheng5** [comment]
OK. Just so you know, you may have problems with this again in the future, due to some heavy refactoring we're doing inside httpuv; the upshot would be `Sys.sleep(0.001)` might need to be replaced with `later::run_now(0.001)` (but not right now).
