### ISSUE TITLE
Incorrect behavior with onHeaders

### ISSUE THREAD

**Issue by wch** [rstudio/httpuv#96]
As of httpuv 1.3.5, the `onHeaders()` function does some things incorrectly.

With this test app:

```R
runServer("0.0.0.0", 5000,
  list(
    onHeaders = function(req) {
      list(
        status = 200L,
        headers = list('Content-Type' = 'text/html'),
        body = "abc"
      )
    } 
  )
)
```

Then do a `GET /`:

```
$ nc localhost 5000
GET /

HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 3
```

Two things happen incorrectly (I think):

1. It doesn't return the body ("abc").
2. In the R side, it says there's a parse error, as in `ERROR: [on_request_read] parse error`.

I just tested with Shiny, and indeed it doesn't send the body [here](https://github.com/rstudio/shiny/blob/ba8d79f/R/middleware.R#L303).

After the server sends the data, it closes the connection. This differs from the behavior when `$call()` is used, where the server does not close the connection. Is the disconnection expected?

```
> sessioninfo::session_info()
─ Session info ────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 os       macOS Sierra 10.12.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2017-10-24                  

─ Packages ────────────────────────────────────────────────────────────────────────
 package     * version date       source         
 clisymbols    1.2.0   2017-05-21 cran (@1.2.0)  
 httpuv      * 1.3.5   2017-07-04 CRAN (R 3.4.1) 
 Rcpp          0.12.13 2017-09-28 cran (@0.12.13)
 sessioninfo   1.0.0   2017-06-21 CRAN (R 3.4.1) 
 withr         2.0.0   2017-07-28 cran (@2.0.0)  
 yaml          2.1.14  2016-11-12 CRAN (R 3.4.0) 
```

**Comment by jcheng5** [comment]
I wouldn't expect it to close, no. Doesn't this look OK?
https://github.com/rstudio/httpuv/blob/6a3f65213fb855bd9d300f46467f94443cbbb840/src/http.cpp#L221-L240

**Comment by wch** [comment]
Actually, I suspect that the reason the connection closes is because of the parse error.

**Comment by jcheng5** [comment]
Oh duh, that makes sense. :)
